const categories=["教程","工具","游戏","软件","学习资料","其他"];let resources=[],handle=null,editing=null;
const $=id=>document.getElementById(id), notice=msg=>{$("notice").textContent=msg}; categories.forEach(c=>{$("category").add(new Option(c,c));$("filter").add(new Option(c,c))});
function render(){const q=$("search").value.toLowerCase(),cat=$("filter").value;const list=resources.filter(r=>(cat==='全部'||r.category===cat)&&(`${r.title} ${r.description} ${r.category}`).toLowerCase().includes(q));$("list").innerHTML=list.map(r=>`<article class="item"><div><h3>${escapeHtml(r.title)} ${r.featured?'⭐':''}</h3><p>${escapeHtml(r.description)}</p><div class="meta">${r.category} · ${r.enabled?'上线':'已下架'} · ${r.url||'暂无链接'}</div></div><div class="actions"><button onclick="edit('${r.id}')">编辑</button><button onclick="toggle('${r.id}')">${r.enabled?'下架':'恢复'}</button><button class="danger" onclick="removeItem('${r.id}')">删除</button>${r.url?`<button onclick="copyUrl('${r.id}')">复制链接</button>`:''}</div></article>`).join('')||'<div class="notice">没有匹配资源。</div>'}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function edit(id){const r=resources.find(x=>x.id===id);editing=id;$("editorTitle").textContent='编辑资源';['id','title','description','url'].forEach(k=>$(k).value=r[k]||'');$("category").value=r.category;$("enabled").checked=r.enabled;$("featured").checked=r.featured;$("editor").classList.remove('hidden')}
function reset(){editing=null;$("form").reset();$("id").value='';$("enabled").checked=true;$("editorTitle").textContent='新增资源';$("editor").classList.add('hidden')}
function toggle(id){const r=resources.find(x=>x.id===id);r.enabled=!r.enabled;$("save").disabled=false;render()};function removeItem(id){if(confirm('删除这个资源项目？此操作需要保存才会写入文件。')){resources=resources.filter(r=>r.id!==id);$("save").disabled=false;render()}}function copyUrl(id){navigator.clipboard.writeText(resources.find(r=>r.id===id).url);notice('链接已复制。')}
$("open").onclick=async()=>{if(!window.showOpenFilePicker){notice('当前浏览器不支持文件读写，请使用最新版 Edge 或 Chrome。');return}try{[handle]=await showOpenFilePicker({types:[{description:'JSON',accept:{'application/json':['.json']}}]});resources=JSON.parse(await(await handle.getFile()).text());$("save").disabled=false;notice(`已打开 ${resources.length} 条资源。`);render()}catch(e){if(e.name!=='AbortError')notice('打开失败：'+e.message)}};
$("save").onclick=async()=>{if(!handle)return;try{const writable=await handle.createWritable();await writable.write(JSON.stringify(resources,null,2)+'\n');await writable.close();notice('已保存 resources.json，重新构建网站后生效。')}catch(e){notice('保存失败：'+e.message)}};
$("new").onclick=()=>{reset();$("editor").classList.remove('hidden')};$("cancel").onclick=reset;$("search").oninput=render;$("filter").onchange=render;$("form").onsubmit=e=>{e.preventDefault();const item={id:$("id").value||`resource-${Date.now()}`,title:$("title").value.trim(),category:$("category").value,description:$("description").value.trim(),url:$("url").value.trim(),enabled:$("enabled").checked,featured:$("featured").checked};if(editing){const i=resources.findIndex(r=>r.id===editing);resources[i]=item}else resources.push(item);$("save").disabled=false;reset();render()};render();
